import assert from 'node:assert/strict';import * as THREE from 'three';import fs from 'node:fs/promises';
import {RaceSession,createRaceCourse,validRacePacket,validRaceCourse,formatRaceTime} from '../lib/race-session.ts';
import {GhostRecorder,poseGhost} from '../lib/race-ghost.ts';import {applyWind} from '../lib/race-world.ts';import {createTraversalState} from '../lib/traversal-physics.ts';
const checks=[],check=(name,fn)=>{fn();checks.push(name)};
const course=createRaceCourse([0,30,0],350,320,50);let now=100000;const queue=[],moves={a:[],b:[],c:[]},finishes=[];
const ids=['player-a-2099','player-b-2099','player-c-2099'];
const sessions=ids.map((id,index)=>new RaceSession(id,{send:p=>queue.push(p),teleport:p=>moves[['a','b','c'][index]].push([...p]),started:()=>{},finished:(c,time)=>finishes.push({id,course:c.id,time})}));
const deliver=()=>{while(queue.length){const p=queue.shift();sessions.forEach(s=>s.receive(p,now));}};
const [a,b,c]=sessions;
check('Shared far course and alternating side',()=>{assert.ok(validRaceCourse(course));assert.notEqual(createRaceCourse([0,30,0],350,320,50,course.side).side,course.side);assert.ok(Math.hypot(course.finish[0],course.finish[2])>=640)});
check('Invitation never teleports receivers',()=>{a.invite(course,now,2,'race-1');deliver();assert.equal(b.phase,'invited');assert.equal(moves.b.length,0);assert.equal(moves.c.length,0)});
check('Explicit acceptance and nonparticipant isolation',()=>{b.accept(now);deliver();assert.equal(a.participants.size,2);c.decline(now);assert.equal(c.phase,'free')});
check('Wrong host start rejected',()=>{b.receive({version:1,type:'start',sender:ids[2],raceId:'race-1',sentAt:now,course,participants:ids,until:now+3000},now);assert.equal(b.phase,'invited');});
now+=8000;a.tick(now,course.start);deliver();
check('Same exact start, finish and countdown across clients',()=>{assert.equal(a.phase,'countdown');assert.equal(b.phase,'countdown');assert.equal(a.startAt,b.startAt);assert.deepEqual(a.course,b.course);assert.deepEqual(moves.a[0],moves.b[0]);assert.equal(moves.c.length,0)});
check('Duplicate start does not teleport again',()=>{now+=800;a.tick(now,course.start);deliver();assert.equal(moves.b.length,1)});
now=a.startAt;sessions.forEach(s=>s.tick(now,course.start));
check('Simultaneous racing start',()=>{assert.equal(a.phase,'racing');assert.equal(b.phase,'racing');assert.equal(a.time,b.time)});
now+=22000;b.tick(now,course.finish);deliver();now+=1000;a.tick(now,course.finish);deliver();
check('Finish propagation and one-time completion',()=>{assert.equal(a.results.get(ids[1]),22000);assert.equal(b.results.get(ids[0]),23000);a.tick(now+100,course.finish);assert.equal(finishes.length,2)});
check('Uninvited finish and nonfinite coordinates rejected',()=>{a.receive({version:1,type:'finish',sender:ids[2],raceId:'race-1',sentAt:now,elapsed:1},now);assert.equal(a.results.has(ids[2]),false);assert.equal(validRacePacket({version:1,type:'invite',sender:ids[0],raceId:'bad',sentAt:now,course:{...course,finish:[Infinity,0,0]}}),false)});
check('Solo fallback launches without accepted peers',()=>{const solo=new RaceSession('solo-player',{send:()=>{},teleport:()=>{},started:()=>{},finished:()=>{}});solo.invite(course,now,0,'solo-race');solo.tick(now+501,course.start);assert.equal(solo.phase,'countdown');solo.tick(solo.startAt,course.start);assert.equal(solo.phase,'racing')});
check('Cancelled host invitation resets accepted receiver',()=>{a.invite(course,now,1,'race-2');deliver();b.accept(now);deliver();a.cancel(now);deliver();assert.equal(b.phase,'free')});
check('Timer formats centiseconds',()=>assert.equal(formatRaceTime(65321),'1:05.32'));
const root=new THREE.Group(),surfaceFrame=new THREE.Group(),model=new THREE.Group(),bone=new THREE.Bone();bone.name='test-arm';model.add(bone);surfaceFrame.add(model);root.add(surfaceFrame);const rig={root,surfaceFrame,model},recorder=new GhostRecorder(rig);
root.position.set(4,7,12);bone.rotation.z=.8;recorder.capture(0);root.position.x=14;bone.rotation.z=1.2;recorder.capture(100);
const copy={root:new THREE.Group(),surfaceFrame:new THREE.Group(),model:new THREE.Group()};const copyBone=new THREE.Bone();copyBone.name='test-arm';copy.model.add(copyBone);copy.surfaceFrame.add(copy.model);copy.root.add(copy.surfaceFrame);
check('Ghost preserves complete skeleton and interpolates movement',()=>{poseGhost(copy,recorder.record(course,100),50);assert.ok(Math.abs(copy.root.position.x-9)<1e-5);assert.ok(Math.abs(new THREE.Euler().setFromQuaternion(copyBone.quaternion).z-1)<1e-5)});
const state=createTraversalState({x:10,y:30,z:0},{x:0,y:-10,z:0}),lanes=[{start:new THREE.Vector3(0,30,0),end:new THREE.Vector3(100,30,0),radius:9}];
check('Wind corridor lifts and glides only inside its volume',()=>{assert.equal(applyWind(state,lanes,.1),true);assert.ok(state.velocity.x>0&&state.velocity.y>-10);state.position.z=30;const before={...state.velocity};assert.equal(applyWind(state,lanes,.1),false);assert.deepEqual(state.velocity,before);state.position.z=0;state.grounded=true;assert.equal(applyWind(state,lanes,.1),false)});
await fs.writeFile('docs/verification/racing-report.json',JSON.stringify({passed:true,checks,sharedCourse:course,finishes},null,2)+'\n');console.log(`PASS ${checks.length} race consent, synchronization, timing, ghost and wind checks.`);
